### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by wushuangs** [web-alchemy/fonttools#6]
`PythonError: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/subset/__init__.py", line 3688, in main
    save_font(font, outfile, options)
  File "/lib/python3.11/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/subset/__init__.py", line 3522, in save_font
    font.save(outfile, reorderTables=options.canonical_order)
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 234, in save
    file.write(tmp.getvalue())
OSError: raw write() returned invalid length 23389952 (should have been between 0 and 21092)

    at new_error (/usr/local/lib/node_modules/@web-alchemy/fonttools/node_modules/pyodide/pyodide.asm.js:9:10014)
    at wasm://wasm/02257296:wasm-function[300]:0x158e62
    at wasm://wasm/02257296:wasm-function[301]:0x158f69
    at Module._pythonexc2js (/usr/local/lib/node_modules/@web-alchemy/fonttools/node_modules/pyodide/pyodide.asm.js:9:608600)
    at Module.callPyObjectKwargs (/usr/local/lib/node_modules/@web-alchemy/fonttools/node_modules/pyodide/pyodide.asm.js:9:64408)
    at Module.callPyObject (/usr/local/lib/node_modules/@web-alchemy/fonttools/node_modules/pyodide/pyodide.asm.js:9:65365)
    at _.apply (/usr/local/lib/node_modules/@web-alchemy/fonttools/node_modules/pyodide/pyodide.asm.js:9:79442)
    at Object.apply (/usr/local/lib/node_modules/@web-alchemy/fonttools/node_modules/pyodide/pyodide.asm.js:9:77681)
    at main (/usr/local/lib/node_modules/@web-alchemy/fonttools/modules/subset/cli.js:8:20) {
  type: 'OSError',
  __error_address: 19742000
}

Node.js v18.0.0
Font subsetted successfully to output.ttf`

**Comment by monochromer** [comment]
Please, provide more information about **what** and **how** you do.

**Comment by monochromer** [comment]
Also need information about environment. This issue may be related to Windows WSL.

**Comment by monochromer** [comment]
I am closing the issue because there is not enough information.  If someone reproduces this bug, feel free to reopen.
